Imports System.Resources
Imports System
Imports System.Reflection
Imports System.Runtime.InteropServices

' General Information about an assembly is controlled through the following
' set of attributes. Change these attribute values to modify the information
' associated with an assembly.

' Review the values of the assembly attributes

<Assembly: AssemblyTitle("Garbage Cleaner for SmartBot")>
<Assembly: AssemblyDescription("A plugin that cleans temporary files generated by SmartBot.")>
<Assembly: AssemblyCompany("")>
<Assembly: AssemblyProduct("GarbageCleaner.dll")>
<Assembly: AssemblyCopyright("© ElektroStudios 2019")>
<Assembly: AssemblyTrademark("")>

<Assembly: ComVisible(False)>

'The following GUID is for the ID of the typelib if this project is exposed to COM
<Assembly: Guid("0C989696-2464-46DB-A757-6A4D750B3B14")>

' Version information for an assembly consists of the following four values:
'
'      Major Version
'      Minor Version
'      Build Number
'      Revision
'
' You can specify all the values or you can default the Build and Revision Numbers
' by using the '*' as shown below:
' <Assembly: AssemblyVersion("1.0.*")>

<Assembly: AssemblyVersion("2.3.0.0")>
<Assembly: AssemblyFileVersion("2.3.0.0")>
<Assembly: NeutralResourcesLanguage("en")>
